title: Splashing Photos
email: peter@forret.com
description: Photos from over the world
baseurl: "/"
url: ""
twitter_username: pforret
github_username:  pforret

highlighter:      rouge
permalink:        pretty

paginate:         10

author:
  name:           'Peter Forret'
  url:            https://twitter.com/pforret

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - hyde
  - .idea/
  - _doc
